name: FinalMarket
version: '${project.version}'
main: dev.ender.finalmarket.FinalMarket
api-version: 1.18
authors: [ Ender, RurdCrod ]

commands:
  finalmarket:
    usage: Open shop command gui. This can only be executed on client side.
    permission-message: you dont have the permission to open the gui.
    aliases:
      - fmarket